### ISSUE TITLE
Project Initialisation

### ISSUE THREAD

**Issue by konsalex** [destefanis/design-lint#16]
Hey @destefanis I absolutely loved the idea of Design Lint.

In the end of the README you are saying

> Changing the border radius default
> If you plan on using this app as a private plugin you'll likely want to change the default border radius values which are [0, 2, 4, 8, 16, 24, 32]. This can be acheived by changing these values in App.tsx and in controller.ts.

People and especially designers are going to use it out of the box, so wouldn't be great to set their own best practices or even "scan" their established Figma project and initialise their own design styles?

**Comment by destefanis** [comment]
Hey @konsalex 

This is a great suggestion. I thought a nice in-between was to default to sets of 4 which seems pretty common and then allow users to store their values in local storage! So it's a set once and not until you restart Figma.

The issue is there aren't design styles for border radius set in Figma. So as a developer I'd have to guess as to what is right and what isn't which didn't seem reliable enough or as simple as just a form field.

Hope that makes sense!
